'use client'

/* eslint-disable @typescript-eslint/no-explicit-any */

import { useCallback, useEffect, useRef, useState } from 'react'
import { BarChart3, Download, GripVertical, LayoutDashboard, Loader2, MessageCircle, MoreHorizontal, Paperclip, Phone, Plus, Search, Send, Settings2, Tag as TagIcon, Trash2, Upload, X } from 'lucide-react'
import { createClient } from '@/lib/supabase/client'
import { toast } from 'sonner'

type Board = { id: string; name: string }
type Stage = { id: string; board_id: string; name: string; color: string; position: number }
type Source = { id: string; board_id: string; name: string; color: string }
type Tag = { id: string; board_id: string; name: string; color: string }
type CustomField = { id: string; board_id: string; name: string; field_type: 'text'|'number'|'phone'|'currency'|'date'|'email'|'select'; options: string[]; position: number }
type Lead = { id: string; board_id: string; stage_id: string|null; name: string; company: string|null; phone: string|null; email: string|null; source_id: string|null; value: number|null; tag_ids: string[]; custom_fields: Record<string,string|number>; position: number; created_at: string }
type Contact = { id: string; phone: string; name: string|null; lead_id: string|null }
type Message = { id: string; contact_id: string; direction: 'inbound'|'outbound'; body: string|null; sent_at: string; status: string|null }
type Tab = 'overview'|'crm'|'chats'
type Entity = 'stage'|'source'|'tag'|'field'

const colors = ['#3B82F6','#8B5CF6','#EC4899','#F59E0B','#10B981','#06B6D4','#EF4444','#64748B']
const db = createClient() as any

export function CommercialDashboard() {
  const [tab,setTab] = useState<Tab>('overview')
  const [boards,setBoards] = useState<Board[]>([]); const [boardId,setBoardId] = useState('')
  const [stages,setStages] = useState<Stage[]>([]); const [sources,setSources] = useState<Source[]>([]); const [tags,setTags] = useState<Tag[]>([]); const [fields,setFields] = useState<CustomField[]>([]); const [leads,setLeads] = useState<Lead[]>([])
  const [contacts,setContacts] = useState<Contact[]>([]); const [messages,setMessages] = useState<Message[]>([])
  const [selectedContact,setSelectedContact] = useState(''); const [query,setQuery] = useState(''); const [loading,setLoading] = useState(true)
  const [leadModal,setLeadModal] = useState<{open:boolean;lead?:Lead;stageId?:string}>({open:false})
  const [entityModal,setEntityModal] = useState<{open:boolean;type:Entity}>({open:false,type:'stage'})
  const fileRef = useRef<HTMLInputElement>(null)

  const load = useCallback(async () => {
    setLoading(true)
    const [{data:b},{data:s},{data:o},{data:t},{data:f},{data:l},{data:c},{data:m}] = await Promise.all([
      db.from('crm_boards').select('id,name').order('created_at'), db.from('crm_stages').select('*').order('position'),
      db.from('crm_sources').select('*').order('created_at'), db.from('crm_tags').select('*').order('created_at'),
      db.from('crm_custom_fields').select('*').order('position'), db.from('crm_leads').select('*').order('position'),
      db.from('crm_contacts').select('*').order('created_at',{ascending:false}), db.from('crm_messages').select('*').order('sent_at'),
    ])
    setBoards(b||[]); setStages(s||[]); setSources(o||[]); setTags(t||[]); setFields(f||[]); setLeads(l||[]); setContacts(c||[]); setMessages(m||[])
    setBoardId(current => current || b?.[0]?.id || ''); setSelectedContact(current=>current||c?.[0]?.id||''); setLoading(false)
  },[])
  useEffect(()=>{ void load() },[load])

  const boardStages=stages.filter(x=>x.board_id===boardId), boardSources=sources.filter(x=>x.board_id===boardId), boardTags=tags.filter(x=>x.board_id===boardId), boardFields=fields.filter(x=>x.board_id===boardId), boardLeads=leads.filter(x=>x.board_id===boardId)
  const sourceStats=boardSources.map(source=>({source,count:boardLeads.filter(l=>l.source_id===source.id).length}))
  const activeContact=contacts.find(c=>c.id===selectedContact); const activeMessages=messages.filter(m=>m.contact_id===selectedContact)

  async function createBoard() { const name=prompt('Nome do novo pipeline'); if(!name?.trim())return; const {data,error}=await db.from('crm_boards').insert({name:name.trim()}).select('id,name').single(); if(error)return toast.error(error.message); setBoards((x:Board[])=>[...x,data]);setBoardId(data.id);toast.success('Pipeline criado') }
  async function deleteBoard(){ if(!boardId||!confirm('Excluir este pipeline e todos os seus dados?'))return; await db.from('crm_boards').delete().eq('id',boardId);setBoardId('');await load() }
  async function moveLead(id:string,stage_id:string){ const position=boardLeads.filter(l=>l.stage_id===stage_id).length; setLeads(x=>x.map(l=>l.id===id?{...l,stage_id,position}:l)); const {error}=await db.from('crm_leads').update({stage_id,position}).eq('id',id);if(error){toast.error(error.message);void load()} }
  async function removeEntity(type:Entity,id:string){ const table={stage:'crm_stages',source:'crm_sources',tag:'crm_tags',field:'crm_custom_fields'}[type];if(!confirm('Excluir este item?'))return;const {error}=await db.from(table).delete().eq('id',id);if(error)toast.error(error.message);else void load() }
  function exportCsv(){const head=['nome','empresa','telefone','email','origem','etapa','tags',...boardFields.map(f=>f.name)];const rows=boardLeads.map(l=>[l.name,l.company||'',l.phone||'',l.email||'',boardSources.find(x=>x.id===l.source_id)?.name||'',boardStages.find(x=>x.id===l.stage_id)?.name||'',l.tag_ids.map(id=>boardTags.find(t=>t.id===id)?.name).filter(Boolean).join('|'),...boardFields.map(f=>String(l.custom_fields[f.id]??''))]);const csv=[head,...rows].map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=`${boards.find(b=>b.id===boardId)?.name||'pipeline'}.csv`;a.click();URL.revokeObjectURL(a.href)}
  async function importCsv(file?:File){if(!file||!boardId||!boardStages[0])return toast.error('Crie ao menos uma etapa antes de importar');const text=await file.text();const lines=text.split(/\r?\n/).slice(1).filter(Boolean);const rows=lines.map(line=>{const c=line.split(',').map(v=>v.replace(/^"|"$/g,''));return {board_id:boardId,stage_id:boardStages[0].id,name:c[0]||'Sem nome',company:c[1]||null,phone:c[2]||null,email:c[3]||null,position:0}});const {error}=await db.from('crm_leads').insert(rows);if(error)toast.error(error.message);else{toast.success(`${rows.length} cards importados`);void load()}}

  if(loading)return <div className="h-screen bg-[#07101d] grid place-items-center text-slate-400"><Loader2 className="animate-spin"/></div>
  return <div className="h-screen overflow-hidden bg-[#07101d] text-white flex flex-col">
    <header className="h-16 shrink-0 border-b border-white/[.07] px-5 lg:px-8 flex items-center justify-between bg-[#091525]"><div><h1 className="font-semibold text-lg">Gestão Comercial</h1><p className="text-xs text-slate-500">Central de leads, vendas e relacionamento</p></div><Settings2 size={18} className="text-slate-500"/></header>
    <nav className="h-14 shrink-0 px-5 lg:px-8 flex gap-1 border-b border-white/[.07] bg-[#091525]">{([{id:'overview',label:'Overview',icon:LayoutDashboard},{id:'crm',label:'CRM Kanban',icon:BarChart3},{id:'chats',label:'Chats',icon:MessageCircle}] as const).map(x=><button key={x.id} onClick={()=>setTab(x.id)} className={`flex items-center gap-2 px-4 text-sm border-b-2 ${tab===x.id?'border-blue-500 text-white':'border-transparent text-slate-500'}`}><x.icon size={16}/>{x.label}</button>)}</nav>

    {tab!=='chats'&&<div className="shrink-0 px-5 lg:px-8 py-3 border-b border-white/[.06] flex flex-wrap items-center gap-2 bg-[#081321]"><span className="text-xs text-slate-500">Pipeline</span><select className="control min-w-44" value={boardId} onChange={e=>setBoardId(e.target.value)}><option value="">Nenhum pipeline</option>{boards.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><button className="primary" onClick={createBoard}><Plus size={14}/>Novo pipeline</button>{boardId&&<button className="control text-red-400" onClick={deleteBoard}><Trash2 size={14}/></button>}</div>}

    {tab==='overview'&&<main className="flex-1 overflow-y-auto p-5 lg:p-8">{!boardId?<Empty text="Crie seu primeiro pipeline para visualizar os indicadores." onClick={createBoard}/>:<><h2 className="text-xl font-semibold">{boards.find(b=>b.id===boardId)?.name}</h2><p className="text-sm text-slate-500 mt-1 mb-6">Indicadores gerados exclusivamente pelos dados deste pipeline.</p><div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-4 mb-7"><Metric label="Total de cards" value={boardLeads.length}/>{boardStages.map(s=><Metric key={s.id} label={s.name} value={boardLeads.filter(l=>l.stage_id===s.id).length} color={s.color}/>)}</div><div className="grid xl:grid-cols-2 gap-5"><Panel title="Cards por etapa">{boardStages.length?boardStages.map(s=><Bar key={s.id} name={s.name} count={boardLeads.filter(l=>l.stage_id===s.id).length} total={boardLeads.length} color={s.color}/>):<SmallEmpty text="Nenhuma etapa criada."/>}</Panel><Panel title="Cards por origem">{sourceStats.length?sourceStats.map(({source,count})=><Bar key={source.id} name={source.name} count={count} total={boardLeads.length} color={source.color}/>):<SmallEmpty text="Nenhuma origem criada."/>}</Panel></div></>}</main>}

    {tab==='crm'&&<main className="flex-1 min-h-0 flex flex-col">{!boardId?<div className="flex-1 overflow-y-auto p-8"><Empty text="Crie um pipeline para começar." onClick={createBoard}/></div>:<><div className="shrink-0 p-3 px-5 flex flex-wrap gap-2 border-b border-white/[.06]"><div className="search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar cards..."/></div><button className="control" onClick={()=>setEntityModal({open:true,type:'stage'})}><Plus size={14}/>Etapa</button><button className="control" onClick={()=>setEntityModal({open:true,type:'source'})}><Plus size={14}/>Origem</button><button className="control" onClick={()=>setEntityModal({open:true,type:'tag'})}><TagIcon size={14}/>Tag</button><button className="control" onClick={()=>setEntityModal({open:true,type:'field'})}><Plus size={14}/>Campo personalizado</button><span className="flex-1"/><input ref={fileRef} hidden type="file" accept=".csv" onChange={e=>void importCsv(e.target.files?.[0])}/><button className="control" onClick={()=>fileRef.current?.click()}><Upload size={14}/>CSV</button><button className="control" onClick={exportCsv}><Download size={14}/></button></div><div className="flex-1 min-h-0 overflow-x-auto overflow-y-hidden"><div className="h-full flex gap-4 p-4 min-w-max">{boardStages.map(stage=>{const cards=boardLeads.filter(l=>l.stage_id===stage.id&&(l.name+(l.company||'')).toLowerCase().includes(query.toLowerCase()));return <section key={stage.id} className="w-[310px] h-full flex flex-col rounded-xl bg-[#0a1727] border border-white/[.06]" onDragOver={e=>e.preventDefault()} onDrop={e=>void moveLead(e.dataTransfer.getData('lead'),stage.id)}><header className="shrink-0 p-3 flex items-center gap-2"><span className="w-2.5 h-2.5 rounded-full" style={{background:stage.color}}/><b className="text-sm flex-1 truncate">{stage.name}</b><span className="text-xs text-slate-500">{cards.length}</span><button onClick={()=>void removeEntity('stage',stage.id)}><Trash2 size={13} className="text-slate-600 hover:text-red-400"/></button></header><div className="flex-1 overflow-y-auto px-3">{cards.map(lead=><LeadCard key={lead.id} lead={lead} tags={boardTags} fields={boardFields} onOpen={()=>setLeadModal({open:true,lead})}/>)}</div><button className="shrink-0 m-3 mt-2 py-2 text-xs text-slate-500 hover:text-white border border-dashed border-white/10 rounded-lg" onClick={()=>setLeadModal({open:true,stageId:stage.id})}><Plus size={13} className="inline"/> Adicionar card</button></section>})}<button onClick={()=>setEntityModal({open:true,type:'stage'})} className="w-[280px] h-12 shrink-0 border border-dashed border-white/10 rounded-xl text-sm text-slate-500 hover:text-white"><Plus size={15} className="inline mr-1"/>Nova etapa</button></div></div></>}</main>}

    {tab==='chats'&&<main className="flex-1 min-h-0 grid md:grid-cols-[340px_1fr] overflow-hidden"><aside className="min-h-0 border-r border-white/[.07] flex flex-col"><div className="shrink-0 p-4 border-b border-white/[.07]"><h2 className="font-semibold">Conversas</h2><p className="text-xs text-slate-500 mt-1">Mensagens armazenadas pela YCloud</p></div><div className="flex-1 overflow-y-auto">{contacts.length?contacts.map(c=>{const last=messages.filter(m=>m.contact_id===c.id).at(-1);return <button key={c.id} onClick={()=>setSelectedContact(c.id)} className={`w-full p-4 flex gap-3 text-left border-b border-white/[.05] ${selectedContact===c.id?'bg-blue-500/[.08] border-l-2 border-l-blue-500':''}`}><div className="w-10 h-10 shrink-0 rounded-full bg-slate-700 grid place-items-center text-xs">{(c.name||c.phone).slice(0,2).toUpperCase()}</div><div className="min-w-0"><b className="text-sm block truncate">{c.name||'Contato sem nome'}</b><p className="text-xs text-slate-500 truncate mt-1">{last?.body||c.phone}</p></div></button>}):<SmallEmpty text="Nenhuma conversa recebida."/>}</div></aside><ChatDetail contact={activeContact} messages={activeMessages}/></main>}
    {leadModal.open&&<LeadModal boardId={boardId} stages={boardStages} sources={boardSources} tags={boardTags} fields={boardFields} initial={leadModal.lead} stageId={leadModal.stageId} onClose={()=>setLeadModal({open:false})} onSaved={()=>{setLeadModal({open:false});void load()}}/>}
    {entityModal.open&&<EntityModal type={entityModal.type} boardId={boardId} position={boardStages.length} onClose={()=>setEntityModal(x=>({...x,open:false}))} onSaved={()=>{setEntityModal(x=>({...x,open:false}));void load()}}/>}
  </div>
}

function LeadCard({lead,tags,fields,onOpen}:{lead:Lead;tags:Tag[];fields:CustomField[];onOpen:()=>void}){return <article draggable onDragStart={e=>e.dataTransfer.setData('lead',lead.id)} onClick={onOpen} className="bg-[#101f32] border border-white/[.07] rounded-lg p-3 mb-3 cursor-pointer hover:border-blue-500/40"><div className="flex gap-2"><GripVertical size={15} className="text-slate-600 cursor-grab"/><b className="text-sm flex-1">{lead.name}</b><MoreHorizontal size={15} className="text-slate-600"/></div>{lead.company&&<p className="text-xs text-slate-500 mt-1 ml-6">{lead.company}</p>}<div className="flex flex-wrap gap-1 mt-3">{lead.tag_ids.map(id=>{const t=tags.find(x=>x.id===id);return t?<span key={id} className="text-[10px] px-2 py-1 rounded" style={{background:`${t.color}22`,color:t.color}}>{t.name}</span>:null})}</div>{fields.slice(0,2).map(f=>lead.custom_fields[f.id]!==undefined?<p key={f.id} className="text-[10px] text-slate-500 mt-2"><span>{f.name}:</span> <b className="text-slate-300">{String(lead.custom_fields[f.id])}</b></p>:null)}</article>}
function Metric({label,value,color='#3B82F6'}:{label:string;value:number;color?:string}){return <div className="bg-[#0b192b] border border-white/[.07] rounded-xl p-5"><span className="w-2 h-2 rounded-full block mb-4" style={{background:color}}/><p className="text-xs text-slate-500 truncate">{label}</p><strong className="text-3xl block mt-2">{value}</strong></div>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="bg-[#0b192b] border border-white/[.07] rounded-xl p-5 max-h-[430px] overflow-y-auto"><h3 className="font-medium sticky top-0 bg-[#0b192b] pb-4">{title}</h3><div className="space-y-5">{children}</div></section>}
function Bar({name,count,total,color}:{name:string;count:number;total:number;color:string}){const pct=total?count/total*100:0;return <div><div className="flex justify-between text-sm mb-2"><span className="text-slate-300">{name}</span><b>{count} <span className="font-normal text-slate-600">({Math.round(pct)}%)</span></b></div><div className="h-2 bg-white/5 rounded-full"><div className="h-full rounded-full" style={{width:`${pct}%`,background:color}}/></div></div>}
function Empty({text,onClick}:{text:string;onClick:()=>void}){return <div className="h-72 border border-dashed border-white/10 rounded-xl grid place-items-center text-center"><div><BarChart3 className="mx-auto text-slate-700 mb-3"/><p className="text-sm text-slate-400">{text}</p><button className="primary mt-4" onClick={onClick}><Plus size={14}/>Criar pipeline</button></div></div>}
function SmallEmpty({text}:{text:string}){return <p className="text-sm text-slate-600 p-6 text-center">{text}</p>}

function EntityModal({type,boardId,position,onClose,onSaved}:{type:Entity;boardId:string;position:number;onClose:()=>void;onSaved:()=>void}){
  const [name,setName]=useState('');const [color,setColor]=useState(colors[0]);const [fieldType,setFieldType]=useState<CustomField['field_type']>('text');const labels={stage:'Nova etapa',source:'Nova origem',tag:'Nova tag',field:'Novo campo personalizado'}
  async function save(e:React.FormEvent){e.preventDefault();const table={stage:'crm_stages',source:'crm_sources',tag:'crm_tags',field:'crm_custom_fields'}[type];const value=type==='field'?{board_id:boardId,name,field_type:fieldType,position,options:[]}:{board_id:boardId,name,color,...(type==='stage'?{position}: {})};const {error}=await db.from(table).insert(value);if(error)toast.error(error.message);else onSaved()}
  return <Modal title={labels[type]} onClose={onClose}><form onSubmit={save}><label className="field">Nome<input autoFocus required value={name} onChange={e=>setName(e.target.value)}/></label>{type==='field'?<label className="field">Tipo<select value={fieldType} onChange={e=>setFieldType(e.target.value as CustomField['field_type'])}><option value="text">Texto</option><option value="number">Número</option><option value="phone">Telefone</option><option value="currency">Moeda / faturamento</option><option value="date">Data</option><option value="email">E-mail</option><option value="select">Seleção</option></select></label>:<label className="field">Cor<div className="flex gap-2 mt-2">{colors.map(c=><button type="button" aria-label={c} key={c} onClick={()=>setColor(c)} className={`w-7 h-7 rounded-full ${color===c?'ring-2 ring-white ring-offset-2 ring-offset-[#0d1b2e]':''}`} style={{background:c}}/>)}</div></label>}<Actions onClose={onClose}/></form></Modal>
}
function LeadModal({boardId,stages,sources,tags,fields,initial,stageId,onClose,onSaved}:{boardId:string;stages:Stage[];sources:Source[];tags:Tag[];fields:CustomField[];initial?:Lead;stageId?:string;onClose:()=>void;onSaved:()=>void}){
  const [name,setName]=useState(initial?.name||'');const [company,setCompany]=useState(initial?.company||'');const [phone,setPhone]=useState(initial?.phone||'');const [email,setEmail]=useState(initial?.email||'');const [stage,setStage]=useState(initial?.stage_id||stageId||stages[0]?.id||'');const [source,setSource]=useState(initial?.source_id||'');const [tagIds,setTagIds]=useState<string[]>(initial?.tag_ids||[]);const [custom,setCustom]=useState<Record<string,string|number>>(initial?.custom_fields||{});const [saving,setSaving]=useState(false)
  async function save(e:React.FormEvent){e.preventDefault();setSaving(true);const value={board_id:boardId,name,company:company||null,phone:phone||null,email:email||null,stage_id:stage||null,source_id:source||null,tag_ids:tagIds,custom_fields:custom,position:initial?.position||0};const q=initial?db.from('crm_leads').update(value).eq('id',initial.id):db.from('crm_leads').insert(value);const {error}=await q;setSaving(false);if(error)toast.error(error.message);else onSaved()}
  async function remove(){if(!initial||!confirm('Excluir este card?'))return;const {error}=await db.from('crm_leads').delete().eq('id',initial.id);if(error)toast.error(error.message);else onSaved()}
  return <Modal title={initial?'Editar card':'Novo card'} onClose={onClose} wide><form onSubmit={save} className="grid sm:grid-cols-2 gap-x-4"><label className="field">Nome do card<input autoFocus required value={name} onChange={e=>setName(e.target.value)}/></label><label className="field">Empresa<input value={company} onChange={e=>setCompany(e.target.value)}/></label><label className="field">Telefone<input type="tel" value={phone} onChange={e=>setPhone(e.target.value)}/></label><label className="field">E-mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label className="field">Etapa<select value={stage} onChange={e=>setStage(e.target.value)}>{stages.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className="field">Origem<select value={source} onChange={e=>setSource(e.target.value)}><option value="">Sem origem</option>{sources.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>{fields.map(f=><label className="field" key={f.id}>{f.name}<input type={f.field_type==='date'?'date':f.field_type==='email'?'email':f.field_type==='phone'?'tel':['number','currency'].includes(f.field_type)?'number':'text'} value={custom[f.id]??''} onChange={e=>setCustom(x=>({...x,[f.id]:['number','currency'].includes(f.field_type)?Number(e.target.value):e.target.value}))}/></label>)}<fieldset className="sm:col-span-2 mt-5"><legend className="text-xs text-slate-400 mb-2">Tags</legend><div className="flex flex-wrap gap-2">{tags.map(t=><button type="button" key={t.id} onClick={()=>setTagIds(x=>x.includes(t.id)?x.filter(id=>id!==t.id):[...x,t.id])} className={`text-xs px-3 py-1.5 rounded-full border ${tagIds.includes(t.id)?'ring-1 ring-white/50':'opacity-50'}`} style={{borderColor:t.color,color:t.color,background:`${t.color}18`}}>{t.name}</button>)}</div></fieldset><div className="sm:col-span-2 flex items-center mt-6">{initial&&<button type="button" onClick={remove} className="control text-red-400"><Trash2 size={14}/>Excluir</button>}<span className="flex-1"/><button type="button" className="control mr-2" onClick={onClose}>Cancelar</button><button className="primary" disabled={saving}>{saving&&<Loader2 size={14} className="animate-spin"/>}Salvar</button></div></form></Modal>
}
function Modal({title,onClose,wide,children}:{title:string;onClose:()=>void;wide?:boolean;children:React.ReactNode}){return <div className="fixed inset-0 z-50 bg-black/75 grid place-items-center p-4"><div className={`w-full ${wide?'max-w-2xl':'max-w-md'} max-h-[90vh] overflow-y-auto bg-[#0d1b2e] border border-white/10 rounded-xl p-6`}><header className="flex justify-between"><h2 className="font-semibold">{title}</h2><button onClick={onClose}><X size={18}/></button></header>{children}</div></div>}
function Actions({onClose}:{onClose:()=>void}){return <div className="flex justify-end gap-2 mt-6"><button type="button" className="control" onClick={onClose}>Cancelar</button><button className="primary">Criar</button></div>}
function ChatDetail({contact,messages}:{contact?:Contact;messages:Message[]}){const [text,setText]=useState('');if(!contact)return <div className="grid place-items-center text-sm text-slate-600">Selecione uma conversa</div>;return <section className="min-h-0 flex flex-col"><header className="h-[72px] shrink-0 border-b border-white/[.07] px-5 flex items-center gap-3"><div className="w-10 h-10 rounded-full bg-slate-700 grid place-items-center text-xs">{(contact.name||contact.phone).slice(0,2).toUpperCase()}</div><div className="flex-1"><b className="text-sm">{contact.name||'Contato sem nome'}</b><p className="text-xs text-slate-500">{contact.phone}</p></div><a href={`tel:${contact.phone}`}><Phone size={18} className="text-slate-400"/></a></header><div className="flex-1 overflow-y-auto p-5 lg:p-7 space-y-3 bg-[#07111f]">{messages.map(m=><div key={m.id} className={`flex ${m.direction==='outbound'?'justify-end':'justify-start'}`}><div className={`max-w-[72%] px-4 py-2.5 rounded-xl text-sm ${m.direction==='outbound'?'bg-blue-600 rounded-br-sm':'bg-[#17263a] rounded-bl-sm'}`}><p>{m.body||`Mensagem ${m.status||''}`}</p><p className="text-[9px] opacity-60 text-right mt-1">{new Date(m.sent_at).toLocaleString('pt-BR',{hour:'2-digit',minute:'2-digit',day:'2-digit',month:'2-digit'})}</p></div></div>)}</div><div className="shrink-0 p-4 border-t border-white/[.07] flex gap-3"><button disabled title="Anexos serão enviados pela integração YCloud"><Paperclip size={19} className="text-slate-600"/></button><input value={text} onChange={e=>setText(e.target.value)} disabled className="flex-1 bg-white/[.04] border border-white/[.07] rounded-lg px-4 py-2.5 text-sm" placeholder="Envio outbound requer credenciais YCloud"/><button disabled className="p-2.5 rounded-lg bg-blue-600 opacity-40"><Send size={17}/></button></div></section>}
