'use client'
import Link from 'next/link'
import { usePathname } from 'next/navigation'
import { BookHeart, CalendarDays, ChevronUp, Compass, GraduationCap, Home, Menu, Music2, UserRound, UsersRound } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover'
import { cn } from '@/lib/utils'

const items = [{ href: '/sentinela/overview', label: 'Overview', icon: Home }, { href: '/sentinela/jornada', label: 'Jornada', icon: Compass }, { href: '/sentinela/squad', label: 'Squad', icon: UsersRound }, { href: '/sentinela/academia', label: 'Academia', icon: GraduationCap }, { href: '/sentinela/ensaios', label: 'Ensaios', icon: Music2 }, { href: '/sentinela/diario', label: 'Diário', icon: BookHeart }, { href: '/sentinela/cantata', label: 'Cantata', icon: CalendarDays }, { href: '/sentinela/perfil', label: 'Perfil', icon: UserRound }]
function NavLink({ item, compact = false }: { item: typeof items[number]; compact?: boolean }) { const path = usePathname(); const active = path === item.href; return <Link href={item.href} aria-current={active ? 'page' : undefined} className={cn('sentinela-focus flex items-center gap-3 rounded-xl text-sm transition-colors', compact ? 'flex-col gap-1 px-3 py-2 text-[10px]' : 'px-3 py-2.5', active ? 'bg-amber-300/10 text-amber-200' : 'text-slate-400 hover:bg-white/5 hover:text-white')}><item.icon className="h-4 w-4"/><span>{item.label}</span></Link> }
export function SentinelaNavigation() { return <><aside className="fixed inset-y-0 left-0 z-30 hidden w-64 border-r border-white/10 bg-[#090e17]/95 p-5 lg:flex lg:flex-col"><Link href="/sentinela/overview" className="mb-10 px-3 font-semibold tracking-[.25em]">SENTINELA</Link><nav className="space-y-1" aria-label="Navegação principal">{items.map((item) => <NavLink key={item.href} item={item}/>)}</nav><div className="mt-auto rounded-2xl bg-white/5 p-4"><p className="text-xs text-slate-500">Temporada atual</p><p className="mt-1 text-sm">O Caminho · 2026</p></div></aside><nav aria-label="Navegação móvel" className="fixed inset-x-0 bottom-0 z-40 flex items-center justify-around border-t border-white/10 bg-[#090e17]/95 px-2 pb-[env(safe-area-inset-bottom)] lg:hidden">{items.slice(0, 4).map((item) => <NavLink compact key={item.href} item={item}/>)}<Popover><PopoverTrigger asChild><Button variant="ghost" className="h-auto flex-col gap-1 px-3 py-2 text-[10px] text-slate-400"><Menu/><span>Mais</span><ChevronUp className="absolute right-1 top-1 h-3 w-3"/></Button></PopoverTrigger><PopoverContent align="end" side="top" className="w-52 border-white/10 bg-[#111b2b] text-white">{items.slice(4).map((item) => <NavLink key={item.href} item={item}/>)}</PopoverContent></Popover></nav></> }
