import { ArrowRight, BookOpen, CalendarDays, Check, Clock3, MessageCircle, Target, UsersRound } from 'lucide-react'
import { ModuleHeader } from '../../_components/module-shell'
import { SentinelaAvatar } from '../../_components/sentinela-avatar'
import { currentSeason, milestones, squad } from '../../_lib/season'
export default function OverviewPage() { return <><ModuleHeader eyebrow={`Temporada ${currentSeason.year} · Semana ${currentSeason.week} de ${currentSeason.totalWeeks}`} title="Continue firme, Sentinela." description={`Fase atual: ${currentSeason.phase}. Cada pequena escolha desenha o caminho.`}/><section className="grid gap-5 xl:grid-cols-[1.4fr_.9fr]">
  <article className="sentinela-card rounded-3xl p-6 sm:p-8"><div className="flex items-start justify-between"><div><p className="flex items-center gap-2 text-xs uppercase tracking-widest text-amber-300"><Target/> Missão da semana</p><h2 className="mt-4 text-2xl">{currentSeason.mission.title}</h2><p className="mt-2 max-w-lg text-slate-400">{currentSeason.mission.description}</p></div><SentinelaAvatar className="h-20 w-20 shrink-0"/></div><div className="mt-7 flex items-center gap-4"><div className="h-2 flex-1 overflow-hidden rounded-full bg-white/10"><div className="h-full bg-amber-300" style={{width:`${currentSeason.mission.progress/currentSeason.mission.target*100}%`}}/></div><span className="text-sm">{currentSeason.mission.progress}/{currentSeason.mission.target} dias</span></div></article>
  <article className="sentinela-card rounded-3xl p-6"><p className="flex items-center gap-2 text-xs uppercase tracking-widest text-blue-300"><UsersRound/> Squad Horizonte</p><div className="mt-5 flex -space-x-2">{squad.map(member => <div key={member.name} title={member.name} className="relative grid h-12 w-12 place-items-center rounded-full border-2 border-[#121b2a] bg-slate-700 text-xs">{member.initials}{member.online && <span className="absolute bottom-0 right-0 h-3 w-3 rounded-full border-2 border-[#121b2a] bg-emerald-400"/>}</div>)}</div><p className="mt-4 text-sm text-slate-400">2 pessoas caminham com você agora.</p></article>
  <article className="sentinela-card rounded-3xl p-6 xl:col-span-2"><div className="flex justify-between"><h2 className="font-medium">Marcos da temporada</h2><span className="text-xs text-slate-500">{currentSeason.name}</span></div><ol className="mt-6 grid grid-cols-4 gap-3 sm:grid-cols-8">{milestones.map((milestone, i) => <li key={milestone.label} className="text-center"><span className={`mx-auto grid h-10 w-10 place-items-center rounded-full border ${milestone.status === 'complete' ? 'border-emerald-400/40 bg-emerald-400/10 text-emerald-300' : milestone.status === 'current' ? 'border-amber-300 bg-amber-300 text-slate-950' : 'border-white/10 text-slate-600'}`}>{milestone.status === 'complete' ? <Check/> : i+1}</span><span className="mt-2 block text-[10px] text-slate-400">{milestone.label}</span></li>)}</ol></article>
  {[{icon:CalendarDays, label:'Próximo ensaio', title:currentSeason.rehearsal.title, meta:`${currentSeason.rehearsal.date} · ${currentSeason.rehearsal.time} · ${currentSeason.rehearsal.place}`},{icon:BookOpen,label:currentSeason.content.type,title:currentSeason.content.title,meta:currentSeason.content.duration}].map(card=><article key={card.label} className="sentinela-card rounded-2xl p-5"><p className="flex items-center gap-2 text-xs text-slate-500"><card.icon/>{card.label}</p><h2 className="mt-3 font-medium">{card.title}</h2><p className="mt-1 text-sm text-slate-400">{card.meta}</p><button className="mt-4 flex items-center gap-1 text-sm text-amber-300">Abrir <ArrowRight/></button></article>)}
  <article className="sentinela-card rounded-2xl p-5 xl:col-span-2"><p className="flex items-center gap-2 text-xs text-blue-300"><MessageCircle/> Feedback do mentor</p><blockquote className="mt-3 text-lg text-slate-300">“{currentSeason.feedback}”</blockquote><p className="mt-3 flex items-center gap-2 text-xs text-slate-500"><Clock3/> Atualizado nesta semana</p></article>
  </section></> }
