'use client'
import { useEffect, useState } from 'react'
import { Archive, Copy, MoreHorizontal, Pause, Play, Plus, Search, Workflow as WorkflowIcon } from 'lucide-react'
import { toast } from 'sonner'
import { WorkflowEditor } from './workflow-editor'
import type { Workflow } from './types'

const seed: Workflow[] = [{id:'welcome',name:'Boas-vindas de novos leads',status:'active',lastRun:new Date(Date.now()-7200000).toISOString(),nodes:[{id:'n1',kind:'trigger',category:'Gatilhos',label:'Lead criado',x:100,y:160,config:{event:'Novo lead'}},{id:'n2',kind:'message',category:'Comunicação',label:'Enviar WhatsApp',x:390,y:160,config:{message:'Olá, {{n1.nome}}','credential':'YCloud'},requiresCredential:true}],edges:[{id:'e1',from:'n1',to:'n2'}]}]

export function Automations(){
  const [items,setItems]=useState<Workflow[]>(seed); const [editing,setEditing]=useState<Workflow>(); const [query,setQuery]=useState('')
  useEffect(()=>{const saved=localStorage.getItem('commercial-workflows');if(saved)try{setItems(JSON.parse(saved))}catch{}},[])
  function update(next:Workflow){setItems(x=>x.map(w=>w.id===next.id?next:w));localStorage.setItem('commercial-workflows',JSON.stringify(items.map(w=>w.id===next.id?next:w)));setEditing(next)}
  function create(){const workflow:Workflow={id:crypto.randomUUID(),name:'Workflow sem título',status:'inactive',nodes:[],edges:[]};setItems(x=>[workflow,...x]);setEditing(workflow)}
  function action(id:string,type:'duplicate'|'archive'|'toggle'){setItems(current=>{const target=current.find(x=>x.id===id)!;let next=current;if(type==='duplicate')next=[{...target,id:crypto.randomUUID(),name:`${target.name} (cópia)`,status:'inactive'},...current];else next=current.map(x=>x.id===id?{...x,status:type==='archive'?'archived':x.status==='active'?'inactive':'active'}:x) as Workflow[];localStorage.setItem('commercial-workflows',JSON.stringify(next));return next});toast.success(type==='duplicate'?'Workflow duplicado':type==='archive'?'Workflow arquivado':'Status atualizado')}
  if(editing)return <WorkflowEditor workflow={editing} onChange={update} onClose={()=>setEditing(undefined)}/>
  const filtered=items.filter(x=>x.name.toLowerCase().includes(query.toLowerCase()))
  return <main className="flex-1 min-h-0 overflow-y-auto p-5 lg:p-8" aria-labelledby="automations-title"><div className="flex flex-wrap gap-4 items-end mb-7"><div className="flex-1"><h2 id="automations-title" className="text-xl font-semibold">Automações</h2><p className="text-sm text-slate-500 mt-1">Crie jornadas automáticas para o seu processo comercial.</p></div><button className="primary" onClick={create}><Plus size={15}/>Criar workflow</button></div><label className="search max-w-md mb-5"><Search size={15}/><span className="sr-only">Buscar workflows</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar automações..."/></label><div className="grid gap-3">{filtered.map(w=><article key={w.id} className="bg-[#0b192b] border border-white/[.07] rounded-xl p-4 flex flex-wrap items-center gap-4"><button onClick={()=>setEditing(w)} className="w-10 h-10 rounded-lg bg-blue-500/10 grid place-items-center" aria-label={`Editar ${w.name}`}><WorkflowIcon size={19} className="text-blue-400"/></button><button onClick={()=>setEditing(w)} className="text-left flex-1 min-w-48"><b className="text-sm">{w.name}</b><p className="text-xs text-slate-500 mt-1">Última execução: {w.lastRun?new Date(w.lastRun).toLocaleString('pt-BR'):'Nunca executado'}</p></button><span className={`text-xs px-2.5 py-1 rounded-full ${w.status==='active'?'bg-emerald-500/10 text-emerald-400':w.status==='archived'?'bg-slate-500/10 text-slate-500':'bg-amber-500/10 text-amber-400'}`}>{w.status==='active'?'Ativo':w.status==='archived'?'Arquivado':'Inativo'}</span><button className="control" onClick={()=>action(w.id,'toggle')} aria-label={w.status==='active'?'Desativar workflow':'Ativar workflow'}>{w.status==='active'?<Pause size={14}/>:<Play size={14}/>} {w.status==='active'?'Desativar':'Ativar'}</button><button className="control" onClick={()=>action(w.id,'duplicate')} aria-label="Duplicar workflow"><Copy size={14}/></button><button className="control text-slate-400" onClick={()=>action(w.id,'archive')} aria-label="Arquivar workflow"><Archive size={14}/></button></article>)}{!filtered.length&&<div className="border border-dashed border-white/10 rounded-xl p-12 text-center text-sm text-slate-500"><MoreHorizontal className="mx-auto mb-2"/>Nenhum workflow encontrado.</div>}</div></main>
}
