ALTER TABLE songs
  ADD COLUMN IF NOT EXISTS bpm INTEGER CHECK (bpm IS NULL OR bpm BETWEEN 20 AND 300),
  ADD COLUMN IF NOT EXISTS lyrics_plain TEXT,
  ADD COLUMN IF NOT EXISTS lyrics_synced TEXT,
  ADD COLUMN IF NOT EXISTS album_name TEXT,
  ADD COLUMN IF NOT EXISTS metadata_source TEXT,
  ADD COLUMN IF NOT EXISTS metadata_payload JSONB DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS metadata_fetched_at TIMESTAMPTZ;

