-- Reserved migration version.
--
-- The first Sentinela prototype declared tables that were later replaced by
-- the season/program model in 045_sentinela_program_foundation.sql. Keeping
-- both schemas in the executable migration chain made a clean database fail
-- before it reached the canonical model. The prototype was never consumed by
-- the application; its version remains reserved so deployed migration ledgers
-- are not renumbered.
