-- Reserved migration version.
--
-- This prototype independently recreated sentinela_seasons,
-- sentinela_memberships and sentinela_rehearsals. The canonical tables are
-- created by migrations 045 and 047. Authorization for that schema is applied
-- incrementally by 049_sentinela_schema_correction.sql.
