-- Academy completion is educational data only; no FK or trigger connects it to
-- official milestone/level progression.
create table public.sentinela_academy_areas (id uuid primary key default gen_random_uuid(), season_id uuid not null references public.sentinela_seasons(id) on delete cascade, name text not null, description text, status text not null default 'draft' check(status in('draft','published','archived')), position int not null default 1, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(season_id,id));
create table public.sentinela_academy_modules (id uuid primary key default gen_random_uuid(), season_id uuid not null, area_id uuid not null, title text not null, description text, status text not null default 'draft' check(status in('draft','published','archived')), position int not null default 1, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(season_id,id), foreign key(season_id,area_id) references public.sentinela_academy_areas(season_id,id) on delete cascade);
create table public.sentinela_academy_lessons (id uuid primary key default gen_random_uuid(), season_id uuid not null, module_id uuid not null, title text not null, content jsonb not null default '{}', duration_minutes int check(duration_minutes is null or duration_minutes>=0), status text not null default 'draft' check(status in('draft','published','archived')), position int not null default 1, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(season_id,id), foreign key(season_id,module_id) references public.sentinela_academy_modules(season_id,id) on delete cascade);
create table public.sentinela_academy_publications (id uuid primary key default gen_random_uuid(), season_id uuid not null, lesson_id uuid not null, published_by uuid references public.profiles(id), published_at timestamptz not null default now(), available_from timestamptz, available_until timestamptz, created_at timestamptz not null default now(), unique(season_id,lesson_id), foreign key(season_id,lesson_id) references public.sentinela_academy_lessons(season_id,id) on delete cascade, check(available_until is null or available_from is null or available_until>=available_from));
create table public.sentinela_education_progress (id uuid primary key default gen_random_uuid(), season_id uuid not null, membership_id uuid not null, lesson_id uuid not null, status text not null default 'not_started' check(status in('not_started','in_progress','completed')), progress_percent int not null default 0 check(progress_percent between 0 and 100), started_at timestamptz, completed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(membership_id,lesson_id), foreign key(season_id,membership_id) references public.sentinela_memberships(season_id,id) on delete cascade, foreign key(season_id,lesson_id) references public.sentinela_academy_lessons(season_id,id) on delete cascade);
create table public.sentinela_lesson_notes (id uuid primary key default gen_random_uuid(), season_id uuid not null, membership_id uuid not null, lesson_id uuid not null, body text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), foreign key(season_id,membership_id) references public.sentinela_memberships(season_id,id) on delete cascade, foreign key(season_id,lesson_id) references public.sentinela_academy_lessons(season_id,id) on delete cascade);

create table public.sentinela_checkpoints (id uuid primary key default gen_random_uuid(), season_id uuid not null references public.sentinela_seasons(id) on delete cascade, milestone_id uuid, title text not null, description text, status text not null default 'draft' check(status in('draft','published','archived')), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(season_id,id), foreign key(season_id,milestone_id) references public.sentinela_milestones(season_id,id));
create table public.sentinela_checkpoint_requirements (id uuid primary key default gen_random_uuid(), season_id uuid not null, checkpoint_id uuid not null, title text not null, description text, evidence_required boolean not null default true, position int not null default 1, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(season_id,id), foreign key(season_id,checkpoint_id) references public.sentinela_checkpoints(season_id,id) on delete cascade);
create table public.sentinela_checkpoint_progress (id uuid primary key default gen_random_uuid(), season_id uuid not null, membership_id uuid not null, checkpoint_id uuid not null, status text not null default 'not_started' check(status in('not_started','in_progress','submitted','validated','rejected')), validated_by uuid references public.profiles(id), validated_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(membership_id,checkpoint_id), foreign key(season_id,membership_id) references public.sentinela_memberships(season_id,id) on delete cascade, foreign key(season_id,checkpoint_id) references public.sentinela_checkpoints(season_id,id) on delete cascade, check((status='validated')=(validated_by is not null and validated_at is not null)));
create table public.sentinela_evidence (id uuid primary key default gen_random_uuid(), season_id uuid not null, membership_id uuid not null, checkpoint_progress_id uuid not null references public.sentinela_checkpoint_progress(id) on delete cascade, requirement_id uuid references public.sentinela_checkpoint_requirements(id), storage_path text not null, media_type text, description text, status text not null default 'submitted' check(status in('submitted','approved','rejected')), approved_by uuid references public.profiles(id), approved_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), foreign key(season_id,membership_id) references public.sentinela_memberships(season_id,id) on delete cascade, check(storage_path like season_id::text||'/'||membership_id::text||'/%'), check((status='approved')=(approved_by is not null and approved_at is not null)));
create table public.sentinela_checkpoint_feedback (id uuid primary key default gen_random_uuid(), season_id uuid not null, checkpoint_progress_id uuid not null references public.sentinela_checkpoint_progress(id) on delete cascade, author_membership_id uuid not null, body text not null, visibility text not null default 'participant' check(visibility in('participant','staff')), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), foreign key(season_id,author_membership_id) references public.sentinela_memberships(season_id,id) on delete cascade);

create index sentinela_education_membership_status_idx on public.sentinela_education_progress(membership_id,season_id,status);
create index sentinela_checkpoint_progress_member_status_idx on public.sentinela_checkpoint_progress(membership_id,season_id,status);
create index sentinela_evidence_member_status_idx on public.sentinela_evidence(membership_id,season_id,status);
do $$ declare t text; begin foreach t in array array['sentinela_academy_areas','sentinela_academy_modules','sentinela_academy_lessons','sentinela_academy_publications','sentinela_education_progress','sentinela_lesson_notes','sentinela_checkpoints','sentinela_checkpoint_requirements','sentinela_checkpoint_progress','sentinela_evidence','sentinela_checkpoint_feedback'] loop execute format('alter table public.%I enable row level security',t); end loop; end $$;
do $$ declare t text; begin foreach t in array array['sentinela_academy_areas','sentinela_academy_modules','sentinela_academy_lessons','sentinela_academy_publications','sentinela_checkpoints','sentinela_checkpoint_requirements'] loop execute format('create policy "season read %1$s" on public.%1$I for select using(public.sentinela_has_membership(season_id))',t); execute format('create policy "staff manage %1$s" on public.%1$I for all using(public.sentinela_is_staff(season_id)) with check(public.sentinela_is_staff(season_id))',t); end loop; end $$;
do $$ declare t text; begin foreach t in array array['sentinela_education_progress','sentinela_lesson_notes','sentinela_checkpoint_progress','sentinela_evidence'] loop execute format('create policy "own read %1$s" on public.%1$I for select using(public.sentinela_is_staff(season_id) or exists(select 1 from public.sentinela_memberships m where m.id=membership_id and m.user_id=auth.uid()))',t); end loop; end $$;
create policy "own education progress" on public.sentinela_education_progress for all using(exists(select 1 from public.sentinela_memberships m where m.id=membership_id and m.user_id=auth.uid())) with check(exists(select 1 from public.sentinela_memberships m where m.id=membership_id and m.user_id=auth.uid()));
create policy "own lesson notes" on public.sentinela_lesson_notes for all using(exists(select 1 from public.sentinela_memberships m where m.id=membership_id and m.user_id=auth.uid())) with check(exists(select 1 from public.sentinela_memberships m where m.id=membership_id and m.user_id=auth.uid()));
create policy "participants submit checkpoint progress" on public.sentinela_checkpoint_progress for insert with check(exists(select 1 from public.sentinela_memberships m where m.id=membership_id and m.user_id=auth.uid()) and status in('not_started','in_progress','submitted') and validated_by is null and validated_at is null);
create policy "participants update unvalidated checkpoint" on public.sentinela_checkpoint_progress for update using(exists(select 1 from public.sentinela_memberships m where m.id=membership_id and m.user_id=auth.uid()) and status<>'validated') with check(status in('not_started','in_progress','submitted') and validated_by is null and validated_at is null);
create policy "participants submit evidence" on public.sentinela_evidence for insert with check(exists(select 1 from public.sentinela_memberships m where m.id=membership_id and m.user_id=auth.uid()) and status='submitted' and approved_by is null and approved_at is null);
do $$ declare t text; begin foreach t in array array['sentinela_education_progress','sentinela_lesson_notes','sentinela_checkpoint_progress','sentinela_evidence','sentinela_checkpoint_feedback'] loop execute format('create policy "staff manage %1$s" on public.%1$I for all using(public.sentinela_is_staff(season_id)) with check(public.sentinela_is_staff(season_id))',t); end loop; end $$;
create policy "feedback visibility" on public.sentinela_checkpoint_feedback for select using(public.sentinela_is_staff(season_id) or (visibility='participant' and exists(select 1 from public.sentinela_checkpoint_progress cp join public.sentinela_memberships m on m.id=cp.membership_id where cp.id=checkpoint_progress_id and m.user_id=auth.uid())));
