-- Practice, community and private reflection.
create table public.sentinela_rehearsals (id uuid primary key default gen_random_uuid(), season_id uuid not null references public.sentinela_seasons(id) on delete cascade, phase_id uuid, title text not null, starts_at timestamptz not null, ends_at timestamptz, location text, notes text, status text not null default 'scheduled' check(status in('scheduled','completed','cancelled')), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(season_id,id), foreign key(season_id,phase_id) references public.sentinela_phases(season_id,id), check(ends_at is null or ends_at>=starts_at));
create table public.sentinela_attendance (id uuid primary key default gen_random_uuid(), season_id uuid not null, rehearsal_id uuid not null, membership_id uuid not null, status text not null default 'expected' check(status in('expected','present','late','absent','excused')), checked_by uuid references public.profiles(id), checked_at timestamptz, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(rehearsal_id,membership_id), foreign key(season_id,rehearsal_id) references public.sentinela_rehearsals(season_id,id) on delete cascade, foreign key(season_id,membership_id) references public.sentinela_memberships(season_id,id) on delete cascade);
create table public.sentinela_repertoire (id uuid primary key default gen_random_uuid(), season_id uuid not null references public.sentinela_seasons(id) on delete cascade, title text not null, artist text, reference_url text, status text not null default 'active' check(status in('active','archived')), metadata jsonb not null default '{}', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(season_id,id));
create table public.sentinela_rehearsal_repertoire (rehearsal_id uuid not null references public.sentinela_rehearsals(id) on delete cascade, repertoire_id uuid not null references public.sentinela_repertoire(id) on delete cascade, position int not null default 1, notes text, created_at timestamptz not null default now(), primary key(rehearsal_id,repertoire_id));
create table public.sentinela_recordings (id uuid primary key default gen_random_uuid(), season_id uuid not null, owner_membership_id uuid not null, rehearsal_id uuid, repertoire_id uuid, storage_path text not null, title text not null, visibility text not null default 'private' check(visibility in('private','squad','season')), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), foreign key(season_id,owner_membership_id) references public.sentinela_memberships(season_id,id) on delete cascade, foreign key(season_id,rehearsal_id) references public.sentinela_rehearsals(season_id,id), foreign key(season_id,repertoire_id) references public.sentinela_repertoire(season_id,id), check(storage_path like season_id::text||'/'||owner_membership_id::text||'/%'));
create table public.sentinela_journal_entries (id uuid primary key default gen_random_uuid(), season_id uuid not null, membership_id uuid not null, title text, body text not null, storage_path text, week_id uuid, phase_id uuid, milestone_id uuid, mission_id uuid, rehearsal_id uuid, checkpoint_id uuid, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), foreign key(season_id,membership_id) references public.sentinela_memberships(season_id,id) on delete cascade, foreign key(season_id,week_id) references public.sentinela_weeks(season_id,id), foreign key(season_id,phase_id) references public.sentinela_phases(season_id,id), foreign key(season_id,milestone_id) references public.sentinela_milestones(season_id,id), foreign key(season_id,mission_id) references public.sentinela_missions(season_id,id), foreign key(season_id,rehearsal_id) references public.sentinela_rehearsals(season_id,id), foreign key(season_id,checkpoint_id) references public.sentinela_checkpoints(season_id,id), check(storage_path is null or storage_path like season_id::text||'/'||membership_id::text||'/%'));

-- Recognition is not competency and carries no XP semantics.
create table public.sentinela_badges (id uuid primary key default gen_random_uuid(), season_id uuid not null references public.sentinela_seasons(id) on delete cascade, name text not null, description text, visual_asset_url text, status text not null default 'active' check(status in('active','archived')), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(season_id,id));
create table public.sentinela_badge_grants (id uuid primary key default gen_random_uuid(), season_id uuid not null, membership_id uuid not null, badge_id uuid not null, granted_by uuid not null references public.profiles(id), reason text, granted_at timestamptz not null default now(), unique(membership_id,badge_id), foreign key(season_id,membership_id) references public.sentinela_memberships(season_id,id) on delete cascade, foreign key(season_id,badge_id) references public.sentinela_badges(season_id,id) on delete cascade);
create table public.sentinela_privileges (id uuid primary key default gen_random_uuid(), season_id uuid not null references public.sentinela_seasons(id) on delete cascade, name text not null, description text, configuration jsonb not null default '{}', status text not null default 'active' check(status in('active','archived')), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(season_id,id));
create table public.sentinela_privilege_grants (id uuid primary key default gen_random_uuid(), season_id uuid not null, membership_id uuid not null, privilege_id uuid not null, granted_by uuid not null references public.profiles(id), starts_at timestamptz not null default now(), expires_at timestamptz, revoked_at timestamptz, created_at timestamptz not null default now(), foreign key(season_id,membership_id) references public.sentinela_memberships(season_id,id) on delete cascade, foreign key(season_id,privilege_id) references public.sentinela_privileges(season_id,id) on delete cascade, check(expires_at is null or expires_at>=starts_at));
create table public.sentinela_avatars (id uuid primary key default gen_random_uuid(), season_id uuid not null, membership_id uuid not null, visual_asset_url text, configuration jsonb not null default '{}', is_public boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(membership_id), foreign key(season_id,membership_id) references public.sentinela_memberships(season_id,id) on delete cascade);
create table public.sentinela_onboarding (id uuid primary key default gen_random_uuid(), season_id uuid not null, membership_id uuid not null, status text not null default 'not_started' check(status in('not_started','in_progress','completed')), answers jsonb not null default '{}', completed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(membership_id), foreign key(season_id,membership_id) references public.sentinela_memberships(season_id,id) on delete cascade);
create table public.sentinela_diagnostics (id uuid primary key default gen_random_uuid(), season_id uuid not null, membership_id uuid not null, kind text not null check(kind in('baseline','final')), responses jsonb not null default '{}', submitted_at timestamptz, reviewed_by uuid references public.profiles(id), reviewed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(membership_id,kind), foreign key(season_id,membership_id) references public.sentinela_memberships(season_id,id) on delete cascade);

create index sentinela_attendance_member_status_idx on public.sentinela_attendance(membership_id,season_id,status);
create index sentinela_recordings_owner_season_idx on public.sentinela_recordings(owner_membership_id,season_id);
create index sentinela_journal_member_season_idx on public.sentinela_journal_entries(membership_id,season_id);
create index sentinela_badge_grants_member_season_idx on public.sentinela_badge_grants(membership_id,season_id);
create index sentinela_privilege_grants_member_season_idx on public.sentinela_privilege_grants(membership_id,season_id);
do $$ declare t text; begin foreach t in array array['sentinela_rehearsals','sentinela_attendance','sentinela_repertoire','sentinela_rehearsal_repertoire','sentinela_recordings','sentinela_journal_entries','sentinela_badges','sentinela_badge_grants','sentinela_privileges','sentinela_privilege_grants','sentinela_avatars','sentinela_onboarding','sentinela_diagnostics'] loop execute format('alter table public.%I enable row level security',t); end loop; end $$;
do $$ declare t text; begin foreach t in array array['sentinela_rehearsals','sentinela_attendance','sentinela_repertoire','sentinela_badges','sentinela_privileges'] loop execute format('create policy "season read %1$s" on public.%1$I for select using(public.sentinela_has_membership(season_id))',t); execute format('create policy "staff manage %1$s" on public.%1$I for all using(public.sentinela_is_staff(season_id)) with check(public.sentinela_is_staff(season_id))',t); end loop; end $$;
create policy "recording visibility" on public.sentinela_recordings for select using(public.sentinela_is_staff(season_id) or exists(select 1 from public.sentinela_memberships m where m.id=owner_membership_id and m.user_id=auth.uid()) or (visibility='season' and public.sentinela_has_membership(season_id)));
create policy "owner manages recordings" on public.sentinela_recordings for all using(exists(select 1 from public.sentinela_memberships m where m.id=owner_membership_id and m.user_id=auth.uid())) with check(exists(select 1 from public.sentinela_memberships m where m.id=owner_membership_id and m.user_id=auth.uid()));
create policy "staff manage recordings" on public.sentinela_recordings for all using(public.sentinela_is_staff(season_id)) with check(public.sentinela_is_staff(season_id));
create policy "season read rehearsal repertoire" on public.sentinela_rehearsal_repertoire for select using(exists(select 1 from public.sentinela_rehearsals r where r.id=rehearsal_id and public.sentinela_has_membership(r.season_id)));
create policy "staff manage rehearsal repertoire" on public.sentinela_rehearsal_repertoire for all using(exists(select 1 from public.sentinela_rehearsals r where r.id=rehearsal_id and public.sentinela_is_staff(r.season_id))) with check(exists(select 1 from public.sentinela_rehearsals r where r.id=rehearsal_id and public.sentinela_is_staff(r.season_id)));
do $$ declare t text; begin foreach t in array array['sentinela_journal_entries','sentinela_onboarding','sentinela_diagnostics'] loop execute format('create policy "owner manage %1$s" on public.%1$I for all using(exists(select 1 from public.sentinela_memberships m where m.id=membership_id and m.user_id=auth.uid())) with check(exists(select 1 from public.sentinela_memberships m where m.id=membership_id and m.user_id=auth.uid()))',t); execute format('create policy "staff read %1$s" on public.%1$I for select using(public.sentinela_is_staff(season_id))',t); end loop; end $$;
create policy "owner or public avatar read" on public.sentinela_avatars for select using(is_public or public.sentinela_is_staff(season_id) or exists(select 1 from public.sentinela_memberships m where m.id=membership_id and m.user_id=auth.uid()));
create policy "owner manage avatar" on public.sentinela_avatars for all using(exists(select 1 from public.sentinela_memberships m where m.id=membership_id and m.user_id=auth.uid())) with check(exists(select 1 from public.sentinela_memberships m where m.id=membership_id and m.user_id=auth.uid()));
do $$ declare t text; begin foreach t in array array['sentinela_badge_grants','sentinela_privilege_grants'] loop execute format('create policy "owner reads %1$s" on public.%1$I for select using(public.sentinela_is_staff(season_id) or exists(select 1 from public.sentinela_memberships m where m.id=membership_id and m.user_id=auth.uid()))',t); execute format('create policy "staff grants %1$s" on public.%1$I for all using(public.sentinela_is_staff(season_id)) with check(public.sentinela_is_staff(season_id))',t); end loop; end $$;

-- Three private domains. Object names are season-id/owner-membership-id/file.
insert into storage.buckets(id,name,public) values ('sentinela-evidence','sentinela-evidence',false),('sentinela-recordings','sentinela-recordings',false),('sentinela-journal','sentinela-journal',false) on conflict(id) do update set public=false;
create function public.sentinela_owns_storage_path(p_name text)
returns boolean language sql stable security definer set search_path=public
as $$ select exists(select 1 from public.sentinela_memberships m where m.season_id=(storage.foldername(p_name))[1]::uuid and m.id=(storage.foldername(p_name))[2]::uuid and m.user_id=auth.uid() and m.status='active') $$;
revoke all on function public.sentinela_owns_storage_path(text) from public; grant execute on function public.sentinela_owns_storage_path(text) to authenticated;
create policy "sentinela private objects select" on storage.objects for select using(bucket_id in('sentinela-evidence','sentinela-recordings','sentinela-journal') and (public.sentinela_owns_storage_path(name) or public.sentinela_is_staff((storage.foldername(name))[1]::uuid)));
create policy "sentinela private objects insert" on storage.objects for insert with check(bucket_id in('sentinela-evidence','sentinela-recordings','sentinela-journal') and public.sentinela_owns_storage_path(name));
create policy "sentinela private objects update" on storage.objects for update using(bucket_id in('sentinela-evidence','sentinela-recordings','sentinela-journal') and public.sentinela_owns_storage_path(name)) with check(bucket_id in('sentinela-evidence','sentinela-recordings','sentinela-journal') and public.sentinela_owns_storage_path(name));
create policy "sentinela private objects delete" on storage.objects for delete using(bucket_id in('sentinela-evidence','sentinela-recordings','sentinela-journal') and (public.sentinela_owns_storage_path(name) or public.sentinela_is_staff((storage.foldername(name))[1]::uuid)));

-- Public storage remains limited to explicitly publishable shared visuals.
insert into storage.buckets(id,name,public) values('sentinela-avatar-assets','sentinela-avatar-assets',true) on conflict(id) do update set public=true;
create policy "staff publish avatar assets" on storage.objects for insert with check(bucket_id='sentinela-avatar-assets' and exists(select 1 from public.sentinela_memberships m where m.user_id=auth.uid() and m.status='active' and m.role in('mentor','journey_admin')));

-- Apply the project's standard updated_at trigger to every mutable Sentinela row.
do $$ declare t text; begin foreach t in array array[
 'sentinela_seasons','sentinela_memberships','sentinela_phases','sentinela_weeks','sentinela_milestones','sentinela_levels','sentinela_competency_progress',
 'sentinela_responsibilities','sentinela_squads','sentinela_missions','sentinela_mission_assignments','sentinela_academy_areas','sentinela_academy_modules',
 'sentinela_academy_lessons','sentinela_education_progress','sentinela_lesson_notes','sentinela_checkpoints','sentinela_checkpoint_requirements',
 'sentinela_checkpoint_progress','sentinela_evidence','sentinela_checkpoint_feedback','sentinela_rehearsals','sentinela_attendance','sentinela_repertoire',
 'sentinela_recordings','sentinela_journal_entries','sentinela_badges','sentinela_privileges','sentinela_avatars','sentinela_onboarding','sentinela_diagnostics'
] loop execute format('create trigger update_%1$s_updated_at before update on public.%1$I for each row execute function public.update_updated_at_column()',t); end loop; end $$;
